//
// Generated file, do not edit! Created by opp_msgc 4.2 from src/base/messages/OutOfNeighborhood.msg.
//

#ifndef _OUTOFNEIGHBORHOOD_M_H_
#define _OUTOFNEIGHBORHOOD_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/base/messages/OutOfNeighborhood.msg</tt> by opp_msgc.
 * <pre>
 * message OutOfNeighborhoodMessage {
 * 
 * 	double outOfNeighborhoodTime;
 * 
 * }
 * </pre>
 */
class OutOfNeighborhoodMessage : public ::cMessage
{
  protected:
    double outOfNeighborhoodTime_var;

  private:
    void copy(const OutOfNeighborhoodMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OutOfNeighborhoodMessage&);

  public:
    OutOfNeighborhoodMessage(const char *name=NULL, int kind=0);
    OutOfNeighborhoodMessage(const OutOfNeighborhoodMessage& other);
    virtual ~OutOfNeighborhoodMessage();
    OutOfNeighborhoodMessage& operator=(const OutOfNeighborhoodMessage& other);
    virtual OutOfNeighborhoodMessage *dup() const {return new OutOfNeighborhoodMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual double getOutOfNeighborhoodTime() const;
    virtual void setOutOfNeighborhoodTime(double outOfNeighborhoodTime);
};

inline void doPacking(cCommBuffer *b, OutOfNeighborhoodMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OutOfNeighborhoodMessage& obj) {obj.parsimUnpack(b);}


#endif // _OUTOFNEIGHBORHOOD_M_H_
